[package]
name        = "charset-locale"
description = "Flix wrappers for Charset and Locale from the JDK"
version     = "0.16.3"
flix        = "0.75.3"
license     = "Apache-2.0"
authors     = ["Stephen Tetley <stephen.tetley@gmail.com>"]

[dependencies]
"github:stephentetley/effect-extras" = { version = "0.4.2", security = "unrestricted" }


