[package]
name        = "charset-locale"
description = "Flix wrappers for Charset and Locale from the JDK"
version     = "0.7.0"
flix        = "0.53.0"
license     = "Apache-2.0"
authors     = ["Stephen Tetley <stephen.tetley@gmail.com>"]


