[package]
name        = "charset-locale"
description = "Flix warppers for Charset and Locale from the JDK"
version     = "0.3.0"
flix        = "0.45.0"
license     = "Apache-2.0"
authors     = ["Stephen Tetley <stephen.tetley@gmail.com>"]


