[package]
name        = "charset-locale"
description = "Flix wrappers for Charset and Locale from the JDK"
version     = "0.9.0"
flix        = "0.56.0"
license     = "Apache-2.0"
authors     = ["Stephen Tetley <stephen.tetley@gmail.com>"]


